"""add cascade delete

Revision ID: 5190809011e3
Revises: 7aca12b95730
Create Date: 2023-09-27 21:14:54.451995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5190809011e3'
down_revision: Union[str, None] = '7aca12b95730'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('link_section_id_fkey', 'link', type_='foreignkey')
    op.create_foreign_key("link_section_id_fkey", 'link', 'section', ['section_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('section_user_id_fkey', 'section', type_='foreignkey')
    op.create_foreign_key("section_user_id_fkey", 'section', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("section_user_id_fkey", 'section', type_='foreignkey')
    op.create_foreign_key('section_user_id_fkey', 'section', 'user', ['user_id'], ['id'])
    op.drop_constraint("link_section_id_fkey", 'link', type_='foreignkey')
    op.create_foreign_key('link_section_id_fkey', 'link', 'section', ['section_id'], ['id'])
    # ### end Alembic commands ###
